# Generated by Django 4.1.6 on 2024-11-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='criticalcon',
            new_name='critical_con',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='personaldoc',
            new_name='personal_doc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='jsondata',
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsondata', models.FileField(upload_to='')),
                ('pat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displaysite.patient')),
            ],
        ),
    ]
