# Generated by Django 4.1.6 on 2024-11-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0002_rename_criticalcon_patient_critical_con_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_num',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
