# Generated by Django 4.1.6 on 2024-11-28 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0003_patient_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='newest_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
