# Generated by Django 4.1.6 on 2024-11-28 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0004_patient_newest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='newest_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
