# Generated by Django 4.1.6 on 2024-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0006_rename_newest_update_data_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='newest_update',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
