# Generated by Django 5.1.3 on 2024-12-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0008_alter_patient_newest_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='patientdata',
        ),
    ]
